### ISSUE TITLE
Missing hermes dSYM

### ISSUE THREAD

**Issue by ebaynaud** [bugsnag/cocoapods-bugsnag#30]
### Describe the bug
App dSYM is uploaded but missing hermes dSYM

![Screenshot 2023-02-06 at 21 00 30](https://user-images.githubusercontent.com/1921301/217073060-76232332-aed9-4329-86c5-f96a78ad34ee.png)

### Steps to reproduce
Enable Hermes (default for latest react-native version) and build!

**Comment by johnkiely1** [comment]
Hi @ebaynaud 

Are you able to check if a matching dSYM has been generated? You can run `mdfind YOUR_UUID_HERE` on the machine the build was produced.  https://docs.bugsnag.com/platforms/ios/symbolication-guide/#troubleshooting-for-apps-without-bitcode. 

However I suspect this may be due to the lack of Hermes debug symbols included in the bundled version. https://reactnative.dev/architecture/bundled-hermes. In other words the debug symbols for Hermes code are simply not included in the upload send to Bugsnag because they don't exist at build time. 

Are you seeing events that are failing to symbolicate because of this missing dSYM? You may find that events will be symbolicated, enough to debug them, as only the Hermes specific lines of the trace would remain unsymbolicated.

**Comment by abigailbramble** [comment]
Going to close this thread due to inactivity. If you continue to experience any issues, feel free to write back on this thread and we can reopen it. Alternatively, you can write into support@bugsnag.com.

**Comment by ebaynaud** [comment]
@johnkiely1 your analysis [sounds right](https://reactnative.dev/architecture/bundled-hermes#debug-symbols).

That's not a really annoying issue, I was simply wondering why I got this missing dSYM listed.
